package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA



/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private int idBairro;
     private Cidade cidade;
     private String bairro;

    public Bairro() {
    }

    public Bairro(int idBairro, Cidade cidade, String bairro) {
       this.idBairro = idBairro;
       this.cidade = cidade;
       this.bairro = bairro;
    }
   
    public int getIdBairro() {
        return this.idBairro;
    }
    
    public void setIdBairro(int idBairro) {
        this.idBairro = idBairro;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }




}


