package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private char tipo;
     private String nomeFantasia;
     private Set documentoses = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int codigo, String nome, char tipo) {
        this.codigo = codigo;
        this.nome = nome;
        this.tipo = tipo;
    }
    public Cliente(int codigo, String nome, char tipo, String nomeFantasia, Set documentoses) {
       this.codigo = codigo;
       this.nome = nome;
       this.tipo = tipo;
       this.nomeFantasia = nomeFantasia;
       this.documentoses = documentoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public char getTipo() {
        return this.tipo;
    }
    
    public void setTipo(char tipo) {
        this.tipo = tipo;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public Set getDocumentoses() {
        return this.documentoses;
    }
    
    public void setDocumentoses(Set documentoses) {
        this.documentoses = documentoses;
    }




}


