package br.com.sysmanager.model;
// Generated 03/09/2009 15:09:26 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Kits generated by hbm2java
 */
public class Kit  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private BigDecimal preco;
     private Set kitsProdutoses = new HashSet(0);

    public Kit() {
    }

	
    public Kit(int codigo, String nome, BigDecimal preco) {
        this.codigo = codigo;
        this.nome = nome;
        this.preco = preco;
    }
    public Kit(int codigo, String nome, BigDecimal preco, Set kitsProdutoses) {
       this.codigo = codigo;
       this.nome = nome;
       this.preco = preco;
       this.kitsProdutoses = kitsProdutoses;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public Set getKitsProdutoses() {
        return this.kitsProdutoses;
    }
    
    public void setKitsProdutoses(Set kitsProdutoses) {
        this.kitsProdutoses = kitsProdutoses;
    }




}


