package br.com.sysmanager.model;
// Generated 03/09/2009 15:09:26 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * KitsProdutos generated by hbm2java
 */
public class KitsProdutos  implements java.io.Serializable {


     private KitsProdutosId id;
     private Produto produto;
     private Kit kits;
     private BigDecimal quantidadeProduto;

    public KitsProdutos() {
    }

	
    public KitsProdutos(KitsProdutosId id, Produto produto, Kit kits) {
        this.id = id;
        this.produto = produto;
        this.kits = kits;
    }
    public KitsProdutos(KitsProdutosId id, Produto produto, Kit kits, BigDecimal quantidadeProduto) {
       this.id = id;
       this.produto = produto;
       this.kits = kits;
       this.quantidadeProduto = quantidadeProduto;
    }
   
    public KitsProdutosId getId() {
        return this.id;
    }
    
    public void setId(KitsProdutosId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Kit getKits() {
        return this.kits;
    }
    
    public void setKits(Kit kits) {
        this.kits = kits;
    }
    public BigDecimal getQuantidadeProduto() {
        return this.quantidadeProduto;
    }
    
    public void setQuantidadeProduto(BigDecimal quantidadeProduto) {
        this.quantidadeProduto = quantidadeProduto;
    }




}


