package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private ProdutoId id;
     private UnidadeMedida unidadeMedida;
     private Grupos grupos;
     private String descricao;
     private BigDecimal quantidadeEstoque;
     private BigDecimal precoAtacado;
     private BigDecimal precoVarejo;
     private BigDecimal quantidadeMinimo;

    public Produto() {
    }

	
    public Produto(ProdutoId id, UnidadeMedida unidadeMedida, Grupos grupos, String descricao, BigDecimal quantidadeEstoque) {
        this.id = id;
        this.unidadeMedida = unidadeMedida;
        this.grupos = grupos;
        this.descricao = descricao;
        this.quantidadeEstoque = quantidadeEstoque;
    }
    public Produto(ProdutoId id, UnidadeMedida unidadeMedida, Grupos grupos, String descricao, BigDecimal quantidadeEstoque, BigDecimal precoAtacado, BigDecimal precoVarejo, BigDecimal quantidadeMinimo) {
       this.id = id;
       this.unidadeMedida = unidadeMedida;
       this.grupos = grupos;
       this.descricao = descricao;
       this.quantidadeEstoque = quantidadeEstoque;
       this.precoAtacado = precoAtacado;
       this.precoVarejo = precoVarejo;
       this.quantidadeMinimo = quantidadeMinimo;
    }
   
    public ProdutoId getId() {
        return this.id;
    }
    
    public void setId(ProdutoId id) {
        this.id = id;
    }
    public UnidadeMedida getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(UnidadeMedida unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public Grupos getGrupos() {
        return this.grupos;
    }
    
    public void setGrupos(Grupos grupos) {
        this.grupos = grupos;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getQuantidadeEstoque() {
        return this.quantidadeEstoque;
    }
    
    public void setQuantidadeEstoque(BigDecimal quantidadeEstoque) {
        this.quantidadeEstoque = quantidadeEstoque;
    }
    public BigDecimal getPrecoAtacado() {
        return this.precoAtacado;
    }
    
    public void setPrecoAtacado(BigDecimal precoAtacado) {
        this.precoAtacado = precoAtacado;
    }
    public BigDecimal getPrecoVarejo() {
        return this.precoVarejo;
    }
    
    public void setPrecoVarejo(BigDecimal precoVarejo) {
        this.precoVarejo = precoVarejo;
    }
    public BigDecimal getQuantidadeMinimo() {
        return this.quantidadeMinimo;
    }
    
    public void setQuantidadeMinimo(BigDecimal quantidadeMinimo) {
        this.quantidadeMinimo = quantidadeMinimo;
    }




}


