package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadeMedida generated by hbm2java
 */
public class UnidadeMedida  implements java.io.Serializable {


     private int codigo;
     private String descricao;
     private String sigla;
     private Integer valor;
     private Set produtos = new HashSet(0);

    public UnidadeMedida() {
    }

	
    public UnidadeMedida(int codigo) {
        this.codigo = codigo;
    }
    public UnidadeMedida(int codigo, String descricao, String sigla, Integer valor, Set produtos) {
       this.codigo = codigo;
       this.descricao = descricao;
       this.sigla = sigla;
       this.valor = valor;
       this.produtos = produtos;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Integer getValor() {
        return this.valor;
    }
    
    public void setValor(Integer valor) {
        this.valor = valor;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


