package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer idCidade;
     private String cidade;
     private int idEstado;
     private Set bairros = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(String cidade, int idEstado) {
        this.cidade = cidade;
        this.idEstado = idEstado;
    }
    public Cidade(String cidade, int idEstado, Set bairros) {
       this.cidade = cidade;
       this.idEstado = idEstado;
       this.bairros = bairros;
    }
   
    public Integer getIdCidade() {
        return this.idCidade;
    }
    
    public void setIdCidade(Integer idCidade) {
        this.idCidade = idCidade;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public int getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(int idEstado) {
        this.idEstado = idEstado;
    }
    public Set getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Set bairros) {
        this.bairros = bairros;
    }




}


