package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA



/**
 * Documentos generated by hbm2java
 */
public class Documentos  implements java.io.Serializable {


     private int clienteCodigo;
     private Cliente cliente;
     private String tipo;
     private String valor;

    public Documentos() {
    }

	
    public Documentos(int clienteCodigo, Cliente cliente) {
        this.clienteCodigo = clienteCodigo;
        this.cliente = cliente;
    }
    public Documentos(int clienteCodigo, Cliente cliente, String tipo, String valor) {
       this.clienteCodigo = clienteCodigo;
       this.cliente = cliente;
       this.tipo = tipo;
       this.valor = valor;
    }
   
    public int getClienteCodigo() {
        return this.clienteCodigo;
    }
    
    public void setClienteCodigo(int clienteCodigo) {
        this.clienteCodigo = clienteCodigo;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getValor() {
        return this.valor;
    }
    
    public void setValor(String valor) {
        this.valor = valor;
    }




}


