package br.com.sysmanager.model;
// Generated 03/09/2009 15:09:26 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * GrupoProduto generated by hbm2java
 */
public class GrupoProduto  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private Set produtos = new HashSet(0);

    public GrupoProduto() {
    }

    public String toString(){
        return this.descricao;
    }
	
    public GrupoProduto(String descricao) {
        this.descricao = descricao;
    }
    public GrupoProduto(String descricao, Set produtos) {
       this.descricao = descricao;
       this.produtos = produtos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


