package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Kits generated by hbm2java
 */
public class Kits  implements java.io.Serializable {


     private int codigo;
     private String nome;
     private BigDecimal preco;

    public Kits() {
    }

    public Kits(int codigo, String nome, BigDecimal preco) {
       this.codigo = codigo;
       this.nome = nome;
       this.preco = preco;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }




}


