package br.com.sysmanager.model;
// Generated 03/09/2009 15:09:26 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer codigo;
     private GrupoProduto grupoProduto;
     private UnidadeMedida unidadeMedida;
     private String descricao;
     private BigDecimal quantidadeEstoque;
     private BigDecimal quantidadeMinimo;
     private BigDecimal precoVenda;
     private BigDecimal precoCompra;
     private Set kitsProdutoses = new HashSet(0);

    public Produto() {
    }

	
    public Produto(GrupoProduto grupoProduto, UnidadeMedida unidadeMedida, String descricao, BigDecimal quantidadeEstoque, BigDecimal quantidadeMinimo, BigDecimal precoVenda, BigDecimal precoCompra) {
        this.grupoProduto = grupoProduto;
        this.unidadeMedida = unidadeMedida;
        this.descricao = descricao;
        this.quantidadeEstoque = quantidadeEstoque;
        this.quantidadeMinimo = quantidadeMinimo;
        this.precoVenda = precoVenda;
        this.precoCompra = precoCompra;
    }
    public Produto(GrupoProduto grupoProduto, UnidadeMedida unidadeMedida, String descricao, BigDecimal quantidadeEstoque, BigDecimal quantidadeMinimo, BigDecimal precoVenda, BigDecimal precoCompra, Set kitsProdutoses) {
       this.grupoProduto = grupoProduto;
       this.unidadeMedida = unidadeMedida;
       this.descricao = descricao;
       this.quantidadeEstoque = quantidadeEstoque;
       this.quantidadeMinimo = quantidadeMinimo;
       this.precoVenda = precoVenda;
       this.precoCompra = precoCompra;
       this.kitsProdutoses = kitsProdutoses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public GrupoProduto getGrupoProduto() {
        return this.grupoProduto;
    }
    
    public void setGrupoProduto(GrupoProduto grupoProduto) {
        this.grupoProduto = grupoProduto;
    }
    public UnidadeMedida getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(UnidadeMedida unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getQuantidadeEstoque() {
        return this.quantidadeEstoque;
    }
    
    public void setQuantidadeEstoque(BigDecimal quantidadeEstoque) {
        this.quantidadeEstoque = quantidadeEstoque;
    }
    public BigDecimal getQuantidadeMinimo() {
        return this.quantidadeMinimo;
    }
    
    public void setQuantidadeMinimo(BigDecimal quantidadeMinimo) {
        this.quantidadeMinimo = quantidadeMinimo;
    }
    public BigDecimal getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(BigDecimal precoVenda) {
        this.precoVenda = precoVenda;
    }
    public BigDecimal getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(BigDecimal precoCompra) {
        this.precoCompra = precoCompra;
    }
    public Set getKitsProdutoses() {
        return this.kitsProdutoses;
    }
    
    public void setKitsProdutoses(Set kitsProdutoses) {
        this.kitsProdutoses = kitsProdutoses;
    }




}


