package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA



/**
 * ProdutoId generated by hbm2java
 */
public class ProdutoId  implements java.io.Serializable {


     private int codigo;
     private int gruposCodigo;

    public ProdutoId() {
    }

    public ProdutoId(int codigo, int gruposCodigo) {
       this.codigo = codigo;
       this.gruposCodigo = gruposCodigo;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public int getGruposCodigo() {
        return this.gruposCodigo;
    }
    
    public void setGruposCodigo(int gruposCodigo) {
        this.gruposCodigo = gruposCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoId) ) return false;
		 ProdutoId castOther = ( ProdutoId ) other; 
         
		 return (this.getCodigo()==castOther.getCodigo())
 && (this.getGruposCodigo()==castOther.getGruposCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCodigo();
         result = 37 * result + this.getGruposCodigo();
         return result;
   }   


}


