package br.com.sysmanager.model;
// Generated 31/08/2009 22:11:06 by Hibernate Tools 3.2.1.GA



/**
 * TiposEnderecos generated by hbm2java
 */
public class TiposEnderecos  implements java.io.Serializable {


     private int codigo;
     private String descricao;

    public TiposEnderecos() {
    }

    public TiposEnderecos(int codigo, String descricao) {
       this.codigo = codigo;
       this.descricao = descricao;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


