package br.com.sysmanager.model;

// Generated 08/09/2009 21:04:24 by Hibernate Tools 3.2.1.GA

import java.io.Serializable;




/**
 * Usuario generated by hbm2java
 */
public class Usuario implements Serializable {

    public Usuario() {
    }

    public Usuario(Integer codigo, String login, String senha) {
        this.codigo = codigo;
        this.login = login;
        this.senha = senha;
    }


     private Integer codigo;
     private String login;
     private String senha;

    /**
     * @return the codigo
     */
    public Integer getCodigo() {
        return codigo;
    }

    /**
     * @param codigo the codigo to set
     */
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }

    /**
     * @return the login
     */
    public String getLogin() {
        return login;
    }


    /**
     * @param login the login to set
     */
    public void setLogin(String login) {
        this.login = login;
    }

    /**
     * @return the senha
     */
    public String getSenha() {
        return senha;
    }

    /**
     * @param senha the senha to set
     */
    public void setSenha(String senha) {
        this.senha = senha;
    }

  

  


}


