package br.com.sysmanager.model;
// Generated 16/10/2009 13:18:29 by Hibernate Tools 3.2.1.GA



/**
 * FornecedoresProdutos generated by hbm2java
 */
public class FornecedoresProdutos  implements java.io.Serializable {


     private FornecedoresProdutosId id;
     private Produto produto;
     private Fornecedor fornecedor;
     
    public FornecedoresProdutos() {
    }

    public FornecedoresProdutos(FornecedoresProdutosId id, Produto produto, Fornecedor fornecedor) {
       this.id = id;
       this.produto = produto;
       this.fornecedor = fornecedor;
    }
   
    public FornecedoresProdutosId getId() {
        return this.id;
    }
    
    public void setId(FornecedoresProdutosId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    
}


