package br.com.sysmanager.model;
// Generated 08/10/2009 12:33:30 by Hibernate Tools 3.2.1.GA



/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private char tipoFornecedor;
     private String nomeFantasia;
     private String email;

    public Fornecedor() {
    }

	
    public Fornecedor(String nome, char tipoFornecedor, String email) {
        this.nome = nome;
        this.tipoFornecedor = tipoFornecedor;
        this.email = email;
    }
    public Fornecedor(String nome, char tipoFornecedor, String nomeFantasia, String email) {
       this.nome = nome;
       this.tipoFornecedor = tipoFornecedor;
       this.nomeFantasia = nomeFantasia;
       this.email = email;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public char getTipoFornecedor() {
        return this.tipoFornecedor;
    }
    
    public void setTipoFornecedor(char tipoFornecedor) {
        this.tipoFornecedor = tipoFornecedor;
    }
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


