package br.com.sysmanager.model;
// Generated 17/09/2009 23:42:50 by Hibernate Tools 3.2.1.GA



/**
 * Cargo generated by hbm2java
 */
public class Cargo  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;

    public Cargo() {
    }

    public Cargo(String descricao) {
       this.descricao = descricao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String toString(){
        return this.descricao;
    }
}


