package br.com.sysmanager.model;
// Generated 07/10/2009 23:24:39 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * Cartao generated by hbm2java
 */
public class Cartao  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private BigDecimal taxa;

    public Cartao() {
    }

	
    public Cartao(String nome) {
        this.nome = nome;
    }
    public Cartao(String nome, BigDecimal taxa) {
       this.nome = nome;
       this.taxa = taxa;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getTaxa() {
        return this.taxa;
    }
    
    public void setTaxa(BigDecimal taxa) {
        this.taxa = taxa;
    }


    public String toString(){
        return this.nome;
    }

}


