package br.com.sysmanager.model;
// Generated 18/09/2009 01:36:54 by Hibernate Tools 3.2.1.GA



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;

    public Departamento() {
    }

    public Departamento(String descricao) {
       this.descricao = descricao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String toString(){
        return this.descricao;
    }

}


