package br.com.sysmanager.model;
// Generated 16/10/2009 13:18:29 by Hibernate Tools 3.2.1.GA



/**
 * FornecedoresProdutosId generated by hbm2java
 */
public class FornecedoresProdutosId  implements java.io.Serializable {


     private int fornecedorCodigo;
     private int produtoCodigo;

    public FornecedoresProdutosId() {
    }

    public FornecedoresProdutosId(int fornecedorCodigo, int produtoCodigo) {
       this.fornecedorCodigo = fornecedorCodigo;
       this.produtoCodigo = produtoCodigo;
    }
   
    public int getFornecedorCodigo() {
        return this.fornecedorCodigo;
    }
    
    public void setFornecedorCodigo(int fornecedorCodigo) {
        this.fornecedorCodigo = fornecedorCodigo;
    }
    public int getProdutoCodigo() {
        return this.produtoCodigo;
    }
    
    public void setProdutoCodigo(int produtoCodigo) {
        this.produtoCodigo = produtoCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FornecedoresProdutosId) ) return false;
		 FornecedoresProdutosId castOther = ( FornecedoresProdutosId ) other; 
         
		 return (this.getFornecedorCodigo()==castOther.getFornecedorCodigo())
 && (this.getProdutoCodigo()==castOther.getProdutoCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getFornecedorCodigo();
         result = 37 * result + this.getProdutoCodigo();
         return result;
   }   


}


