package br.com.sysmanager.model;
// Generated 14/10/2009 02:28:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Kit generated by hbm2java
 */
public class Kit  implements java.io.Serializable {


     private Integer codigo;
     private String nome;
     private BigDecimal preco;
     private Set kitsProdutoses = new HashSet(0);

    public Kit() {
    }

	
    public Kit(String nome, BigDecimal preco) {
        this.nome = nome;
        this.preco = preco;
    }
    public Kit(String nome, BigDecimal preco, Set kitsProdutoses) {
       this.nome = nome;
       this.preco = preco;
       this.kitsProdutoses = kitsProdutoses;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public BigDecimal getPreco() {
        return this.preco;
    }
    
    public void setPreco(BigDecimal preco) {
        this.preco = preco;
    }
    public Set getKitsProdutoses() {
        return this.kitsProdutoses;
    }
    
    public void setKitsProdutoses(Set kitsProdutoses) {
        this.kitsProdutoses = kitsProdutoses;
    }




}


