package br.com.sysmanager.model;
// Generated 14/10/2009 02:28:52 by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * KitsProdutos generated by hbm2java
 */
public class KitsProdutos  implements java.io.Serializable {


     private KitsProdutosId id;
     private Produto produto;
     private Kit kit;
     private BigDecimal quantidadeProduto;

    public KitsProdutos() {
    }

    public KitsProdutos(KitsProdutosId id, Produto produto, Kit kit, BigDecimal quantidadeProduto) {
       this.id = id;
       this.produto = produto;
       this.kit = kit;
       this.quantidadeProduto = quantidadeProduto;
    }
   
    public KitsProdutosId getId() {
        return this.id;
    }
    
    public void setId(KitsProdutosId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Kit getKit() {
        return this.kit;
    }
    
    public void setKit(Kit kit) {
        this.kit = kit;
    }
    public BigDecimal getQuantidadeProduto() {
        return this.quantidadeProduto;
    }
    
    public void setQuantidadeProduto(BigDecimal quantidadeProduto) {
        this.quantidadeProduto = quantidadeProduto;
    }




}


