package br.com.sysmanager.model;
// Generated 09/10/2009 01:22:40 by Hibernate Tools 3.2.1.GA



/**
 * TipoEndereco generated by hbm2java
 */
public class TipoEndereco  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;

    public TipoEndereco() {
    }

    public TipoEndereco(String descricao) {
       this.descricao = descricao;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String toString(){
        return this.descricao;
    }


}


