package br.com.sysmanager.model;
// Generated 06/10/2009 21:13:06 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadeMedida generated by hbm2java
 */
public class UnidadeMedida  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private String sigla;
     private int quantidadeUnidade;
     private Set produtos = new HashSet(0);

    public UnidadeMedida() {
    }

	
    public UnidadeMedida(String descricao, String sigla, int quantidadeUnidade) {
        this.descricao = descricao;
        this.sigla = sigla;
        this.quantidadeUnidade = quantidadeUnidade;
    }
    public UnidadeMedida(String descricao, String sigla, int quantidadeUnidade, Set produtos) {
       this.descricao = descricao;
       this.sigla = sigla;
       this.quantidadeUnidade = quantidadeUnidade;
       this.produtos = produtos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public int getQuantidadeUnidade() {
        return this.quantidadeUnidade;
    }
    
    public void setQuantidadeUnidade(int quantidadeUnidade) {
        this.quantidadeUnidade = quantidadeUnidade;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }

    public String toString(){
        return this.descricao;
    }
    
}


