package br.com.sysmanager.beans;
// Generated 26/08/2009 23:40:07 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UnidadeMedida generated by hbm2java
 */
public class UnidadeMedida  implements java.io.Serializable {


     private Integer codigo;
     private String descricao;
     private String sigla;
     private Set produtos = new HashSet(0);

    public UnidadeMedida() {
    }

	
    public UnidadeMedida(String descricao, String sigla) {
        this.descricao = descricao;
        this.sigla = sigla;
    }
    public UnidadeMedida(String descricao, String sigla, Set produtos) {
       this.descricao = descricao;
       this.sigla = sigla;
       this.produtos = produtos;
    }
   
    public Integer getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Integer codigo) {
        this.codigo = codigo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


