/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frm_Usuario.java
 *
 * Created on 31/08/2009, 23:37:40
 */

package br.com.sysmanager.view;

/**
 *
 * @author manoel.neto
 */
public class frm_Usuario extends javax.swing.JFrame {
String titulo = "Cadastro de Usuário";

    /** Creates new form frm_Usuario */
    public frm_Usuario() {
        initComponents();
    }
private void sair(){
    System.exit(0);
}
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ttl_Titulo = new org.jdesktop.swingx.JXTitledPanel();
        btn_Cancelar = new javax.swing.JButton();
        btn_Excluir = new javax.swing.JButton();
        btn_Salvar = new javax.swing.JButton();
        tab_Usuario = new javax.swing.JTabbedPane();
        pnl_Consulta = new org.jdesktop.swingx.JXPanel();
        lbl_Login1 = new javax.swing.JLabel();
        pnl_Consulta1 = new org.jdesktop.swingx.JXPanel();
        lbl_Senha = new javax.swing.JLabel();
        pwd_Senha = new javax.swing.JPasswordField();
        txt_login = new javax.swing.JTextField();
        lbl_Login = new javax.swing.JLabel();

        setTitle("Cadastro de Usuários");

        ttl_Titulo.setTitle(titulo);
        ttl_Titulo.setTitleFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        btn_Excluir.setText("Excluir");

        btn_Salvar.setText("Salvar");
        btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalvarActionPerformed(evt);
            }
        });

        lbl_Login1.setText("Login");

        javax.swing.GroupLayout pnl_ConsultaLayout = new javax.swing.GroupLayout(pnl_Consulta);
        pnl_Consulta.setLayout(pnl_ConsultaLayout);
        pnl_ConsultaLayout.setHorizontalGroup(
            pnl_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Login1)
                .addContainerGap(414, Short.MAX_VALUE))
        );
        pnl_ConsultaLayout.setVerticalGroup(
            pnl_ConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Login1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        tab_Usuario.addTab("Consulta", null, pnl_Consulta, "Consulta Informações do usuário");

        lbl_Senha.setText("Senha");

        pwd_Senha.setText("teste");
        pwd_Senha.setSelectionStart(5);

        lbl_Login.setText("Login");

        javax.swing.GroupLayout pnl_Consulta1Layout = new javax.swing.GroupLayout(pnl_Consulta1);
        pnl_Consulta1.setLayout(pnl_Consulta1Layout);
        pnl_Consulta1Layout.setHorizontalGroup(
            pnl_Consulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Consulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Consulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_Consulta1Layout.createSequentialGroup()
                        .addComponent(lbl_Login)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Consulta1Layout.createSequentialGroup()
                        .addComponent(lbl_Senha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_Consulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(pwd_Senha, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_login, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        pnl_Consulta1Layout.setVerticalGroup(
            pnl_Consulta1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Consulta1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_login, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwd_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        tab_Usuario.addTab("Cadastro", null, pnl_Consulta1, "Cadastro, Alteração e Excluão de Usuários");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ttl_Titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(251, Short.MAX_VALUE)
                .addComponent(btn_Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Cancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ttl_Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tab_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Cancelar)
                    .addComponent(btn_Excluir)
                    .addComponent(btn_Salvar))
                .addContainerGap())
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-482)/2, (screenSize.height-323)/2, 482, 323);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btn_SalvarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        sair();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Excluir;
    private javax.swing.JButton btn_Salvar;
    private javax.swing.JLabel lbl_Login;
    private javax.swing.JLabel lbl_Login1;
    private javax.swing.JLabel lbl_Senha;
    private org.jdesktop.swingx.JXPanel pnl_Consulta;
    private org.jdesktop.swingx.JXPanel pnl_Consulta1;
    private javax.swing.JPasswordField pwd_Senha;
    private javax.swing.JTabbedPane tab_Usuario;
    private org.jdesktop.swingx.JXTitledPanel ttl_Titulo;
    private javax.swing.JTextField txt_login;
    // End of variables declaration//GEN-END:variables

}
