package br.com.sysmanager.model;
// Generated 03/09/2009 15:09:26 by Hibernate Tools 3.2.1.GA



/**
 * KitsProdutosId generated by hbm2java
 */
public class KitsProdutosId  implements java.io.Serializable {


     private int produtoCodigo;
     private int kitCodigo;

    public KitsProdutosId() {
    }

    public KitsProdutosId(int produtoCodigo, int kitCodigo) {
       this.produtoCodigo = produtoCodigo;
       this.kitCodigo = kitCodigo;
    }
   
    public int getProdutoCodigo() {
        return this.produtoCodigo;
    }
    
    public void setProdutoCodigo(int produtoCodigo) {
        this.produtoCodigo = produtoCodigo;
    }
    public int getKitCodigo() {
        return this.kitCodigo;
    }
    
    public void setKitCodigo(int kitCodigo) {
        this.kitCodigo = kitCodigo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof KitsProdutosId) ) return false;
		 KitsProdutosId castOther = ( KitsProdutosId ) other; 
         
		 return (this.getProdutoCodigo()==castOther.getProdutoCodigo())
 && (this.getKitCodigo()==castOther.getKitCodigo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProdutoCodigo();
         result = 37 * result + this.getKitCodigo();
         return result;
   }   


}


